### ISSUE TITLE
can you generate these firmware?

### ISSUE THREAD

**Issue by PlexPt** [scooterhacking/ninebot-es-snsc-firmware-patcher#4]
https://github.com/PlexPt/ninebot-firmware

**Comment by scooterhacking** [comment]
Hello!
It would require another patcher along with other methods. 
Totally feasible, I would gladly host a toolkit if someone decided to work on it.

**Comment by PlexPt** [comment]
> Hello!
> It would require another patcher along with other methods.
> Totally feasible, I would gladly host a toolkit if someone decided to work on it.
> (Even considering these vehicles might be out of scope for us)

Are you interested in doing one?
