### ISSUE TITLE
Top speed

### ISSUE THREAD

**Issue by miccro0918** [scooterhacking/ninebot-es-snsc-firmware-patcher#5]
Hi, this isn't really an issue but is it possible to get the topspeed up a bit, mine is capping at 32 even if I choose 35. I can feel the wheel breaking so I was wondering if the reason that you capt it at the website is due to brickingrisk or if it's possible to patch it to higher speeds?
/Thanks in advance

**Comment by miccro0918** [comment]
Also would like to extend a huge thank you to the developers. This was by far the easiest and best method of patching Thank you! :)

**Comment by carllarl** [comment]
Hi, it doesn't really matter what value you input there, even if you were to set it to 50 km/h it would still auto break once it hits (in your case) 32 km/h

**Comment by carllarl** [comment]
but if you want to try it, you can just use this link: 

https://ninebot.scooterhacking.org/?max_speed=50

(replace 50 with whatever speed you like) and then pick the other settings you wish to use.

**Comment by scooterhacking** [comment]
The max speed patch only changes a limit in software.
To get a higher top speed, you need bigger wheels or you need to increase the supply voltage.
